/**
 * index.js
 *
 * Master list of test modules
 */

require('./extra/group-lock')
require('./extra/token')

require('./kernel/api')
require('./kernel/auth')
require('./kernel/batch')
require('./kernel/blockchain')
require('./kernel/call')
require('./kernel/caller')
require('./kernel/code')
require('./kernel/deploy')
require('./kernel/destroy')
require('./kernel/jig')
require('./kernel/loader')
require('./kernel/lock')
require('./kernel/membrane')
require('./kernel/native')
require('./kernel/private')
require('./kernel/publish')
require('./kernel/purse')
require('./kernel/recent')
require('./kernel/rules')
require('./kernel/sealed')
require('./kernel/state')
require('./kernel/static')
require('./kernel/sync')
require('./kernel/transaction')
require('./kernel/upgrade')
require('./kernel/universal')

require('./module/mockchain')
require('./module/viewer')

require('./util/admin')
require('./util/bindings')
require('./util/codec')
require('./util/deep')
require('./util/dynamic')
require('./util/log')
require('./util/misc')
require('./util/proxy2')
require('./util/queue')
require('./util/sandbox')
require('./util/standard-lock')
