# Standard checks that run on every push
#
#   Environment: Ubuntu 18.04, Node 12
#
#   - Check if built
#   - Lint
#   - Test code coverage
#   - Test on node
#   - Test on chrome

name: Last Commit

on: push

jobs:
  standard_checks:
    name: Standard Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Lint
      run: npx standard

    - name: Collect Coverage (Mocknet)
      run: npm run test:cover

    - name: Collect Coverage (Testnet)
      run:
        npx nyc --clean=false -r=text -r=lcovonly -x=test/** npm test test/module/blockchain-api.js test/kernel/blockchain.js
      env:
        NETWORK: test
        PURSE: ${{ secrets.PURSE_TESTNET }}

    - name: Test Node
      run: npm run test:node

    - name: Test Browser
      run: npm run test:browser

    - name: Publish Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
