# Standard checks that run on every push
#
#   Environment: Ubuntu 18.04 Linux
#
#   - Lint
#   - Node 12
#   - Chrome

name: Last Commit

on: push

jobs:
  standard_checks:
    name: Standard Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.AUTH_TOKEN }}" > ~/.npmrc
        npm ci

    - name: Lint
      run: npx standard

    - name: Test Node
      run: npm run test:node

    - name: Test Browser
      run: npm run test:browser
